[package]
name = "patterns"
version = "0.1.0"
edition = "2021"
authors = ["Argumate <argumate@argumate.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
